import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import BestPracticesModal from "../components/GoodPracticies";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Conexa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <Header />

        <div className="flex pt-16 min-w-0">
          {/* Sidebar */}
          <div className="shrink-0">
            <Sidebar />
          </div>

          {/* Conteúdo */}
          <div className="flex-1 min-w-0">{children}</div>
        </div>

        <BestPracticesModal />
      </body>
    </html>
  );
}
