import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import BestPracticesModal from "../components/GoodPracticies"; // Importe o componente
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Conexa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <div className="flex pt-16">
          {/* Sidebar fixa */}
          <div className="flex">
            <Sidebar />
          </div>

          <div className="flex-1">{children}</div>
        </div>

        {/* Adicione o componente BestPracticesModal */}
        <BestPracticesModal />
      </body>
    </html>
  );
}
